### ISSUE TITLE
Dead link and example

### ISSUE THREAD

**Issue by Garfield2013** [Symmetronic/discrete-wavelets#11]
Hi there,

Thank you for your interesting module :) I all new to wavelets but I'm trying to use it to smoothening data / denoising signals.

1. FYI: This link here is dead: https://symmetronic.github.io/covid-19-dwt-analysis/ 
2. How do I prune coefficients which I would like to remove - so I can adjust the smoothening level of the signal?

`const coeffs = wt.wavedec(points, waveletType);`

const `prunedCoeffs = ??`

`const smoothedData = wt.waverec(prunedCoeffs, waveletType);`

Thank you so much!

**Comment by Symmetronic** [comment]
Hi @Garfield2013,

sorry for my late reply!

1. Thank you for the notice about the dead link. I just removed it.
2. I also added a note to the `README.md` that I'm currently not able to add any new features or documentation due to limited time.

Best wishes!
